-- ============================================================================
-- 023_024_ledger_registration.sql
--
-- migration 023・024 の台帳（supabase_migrations.schema_migrations）登録記録。
-- 018〜022 の事後登録（018_022_ledger_registration.sql）と同じ位置づけの
-- ファイルであり、migration そのものではないため migrations/ には置かない。
--
-- 023・024 は、018〜022 の登録漏れが判明した経緯（田島様2026-07-29ご指摘1）を
-- 踏まえ、本番適用の直後に台帳登録まで行っている。したがって 018〜022 のような
-- 「事後のまとめ登録」ではなく、適用と同一の作業内で登録済みである。
--
-- 登録済みの内容（2026-07-29 実測で確認）:
--   version 20260729000001 / name 023_b1_ms1_get_my_agency_id_search_path
--   version 20260729000002 / name 024_b1_ms1_candidate_write_functions_and_column_lockdown
--
-- 台帳の連続性: 011・012・013・014・016・017・018・019・020・021・022・023・024
--   （015 は設計協議中のため未適用。台帳に無いことが正しい状態）
--
-- 本ファイルは記録のみで、実行を要する文は含まない。
-- 024 の statements 列の訂正については、別ファイル
-- `024_ledger_fulltext_correction.sql` を参照・実行すること。
-- ============================================================================


-- ── 023 の登録時に実行したSQL（実行済み・再実行不要）───────────────────────
--
-- INSERT INTO supabase_migrations.schema_migrations (version, name, statements)
-- VALUES (
--   '20260729000001',
--   '023_b1_ms1_get_my_agency_id_search_path',
--   ARRAY[
--     'CREATE OR REPLACE FUNCTION public.get_my_agency_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '''' AS $f$ SELECT agency_id FROM public.operator WHERE auth_user_id = auth.uid() AND is_active = true LIMIT 1; $f$'
--   ]
-- ) ON CONFLICT (version) DO NOTHING;
--
-- 023 は1文のみであり、statements 列に実行SQL全文がそのまま格納されている
-- （2026-07-29 実測で確認済み。省略・要約はない）。


-- ── 024 の statements 列について（訂正の経緯）──────────────────────────────
--
-- 024 は当初、statements 列に実行SQL全文ではなく要約文字列
-- （'see repo file for full text: ...'）を格納していた。これを訂正する際、
-- 第1版の訂正SQLでは 2つの CREATE FUNCTION 文の本体を `$$ ... $$` という
-- 省略形で格納しており、要約を格納していた当初の不備と本質的に同じ状態が
-- 残っていた。
--
-- また第1版の自己検査は「配列長11以上」「特定文字列を含まない」しか判定して
-- おらず、本体が省略されたままでも通過してしまう弱い検査であった。
--
-- 現在は `024_ledger_fulltext_correction.sql` により、migrations/024 の
-- 実DDL 11文（CREATE FUNCTION の本体を含む全文）をそのまま格納し、
-- 省略記号の有無・各文の長さ・関数本体の照合ロジックの有無まで判定する
-- 自己検査に置き換えている。
--
-- 検証コマンド（読取のみ）:
--   SELECT i, length(stmt) AS len,
--          (stmt LIKE '%$$ ... $$%' OR stmt LIKE '%see repo file%') AS abbreviated
--     FROM supabase_migrations.schema_migrations sm,
--          LATERAL unnest(sm.statements) WITH ORDINALITY AS t(stmt, i)
--    WHERE sm.version = '20260729000002'
--    ORDER BY i;
--
--   期待値: 11行、abbreviated はすべて false、
--           exclude_candidate の文は 2000字前後、
--           update_candidate_coverage_status の文は 1500字前後。
